import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./template/**/*.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#656461",
        "inverse-surface": "#33302d",
        "on-secondary-fixed": "#1c1c19",
        "error-container": "#ffdad6",
        "on-background": "#1e1b19",
        "on-primary-container": "#bd9f83",
        "tertiary-fixed": "#ccebc7",
        "surface-container-low": "#fffbf9",
        "on-primary": "#ffffff",
        "background": "#fffaf7",
        "inverse-primary": "#e1c1a4",
        "surface-container-highest": "#f7f0eb",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#59422c",
        "on-surface-variant": "#4e453d",
        "primary-container": "#4b3621",
        "secondary": "#5f5e5b",
        "on-error-container": "#93000a",
        "surface": "#fffaf7",
        "surface-container-high": "#f5ede9",
        "on-primary-fixed": "#291806",
        "surface-bright": "#ffffff",
        "on-tertiary-fixed-variant": "#334d33",
        "surface-container": "#faf5f2",
        "on-secondary-fixed-variant": "#474743",
        "surface-dim": "#f2e9e4",
        "secondary-fixed": "#e5e2dd",
        "primary-fixed-dim": "#e1c1a4",
        "on-tertiary-fixed": "#07200b",
        "outline-variant": "#d2c4ba",
        "on-surface": "#1e1b19",
        "on-error": "#ffffff",
        "primary-fixed": "#fedcbe",
        "secondary-fixed-dim": "#c9c6c2",
        "tertiary": "#112a13",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#b0cfad",
        "tertiary-container": "#274027",
        "primary": "#33210d",
        "outline": "#80756c",
        "on-tertiary-container": "#8fac8c",
        "secondary-container": "#e5e2dd",
        "surface-tint": "#725a42",
        "inverse-on-surface": "#f7efeb",
        "surface-variant": "#f0e7e1",
        "surface-container-lowest": "#ffffff",
        "accent-gold": "#d4af37",
        "accent-terracotta": "#c06c4d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "overlap-sm": "-24px",
        "overlap-md": "-48px",
        "margin-mobile": "20px",
        unit: "4px",
        gutter: "24px",
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-playfair)"],
        "label-caps": ["var(--font-inter)"],
        "headline-lg": ["var(--font-playfair)"],
        "display-xl-mobile": ["var(--font-playfair)"],
        "body-sm": ["var(--font-inter)"],
        "display-xl": ["var(--font-playfair)"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-xl-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "900" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-xl": ["84px", { lineHeight: "90px", letterSpacing: "-0.04em", fontWeight: "900" }],
      },
    },
  },
  plugins: [],
};
export default config;