/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./template/**/*.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffdcc5",
        "surface-container-low": "#f9f3eb",
        "inverse-on-surface": "#f7f0e8",
        "pastel-pink-500": "#FF406C",
        "surface-dim": "#dfd9d1",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "surface-tint": "#805533",
        "secondary-fixed-dim": "#feb2c3",
        "secondary-container": "#feb2c3",
        "on-secondary-fixed": "#370b1a",
        "primary-fixed-dim": "#f4bb92",
        "inverse-primary": "#f4bb92",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#301400",
        "primary-container": "#8b5e3c",
        "primary": "#6f4627",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdf98",
        "background": "#fff8f1",
        "on-surface": "#1e1b17",
        "surface": "#fff8f1",
        "on-surface-variant": "#51443c",
        "gold-500": "#FFC726",
        "on-background": "#1e1b17",
        "on-error-container": "#93000a",
        "tertiary-container": "#836300",
        "error": "#ba1a1a",
        "surface-container-high": "#eee7df",
        "on-tertiary-fixed-variant": "#5a4300",
        "secondary-fixed": "#ffd9e0",
        "surface-variant": "#e8e1da",
        "terracotta-500": "#c06c4d",
        "tertiary-fixed-dim": "#f6bf1a",
        "on-tertiary-container": "#ffe5ae",
        "outline-variant": "#d5c3b8",
        "on-primary-fixed-variant": "#653d1e",
        "surface-card": "#FFFFFF",
        "surface-container": "#f4ede5",
        "on-secondary-fixed-variant": "#6c3644",
        "secondary": "#884d5c",
        "tertiary": "#654c00",
        "on-primary-container": "#ffe3d1",
        "inverse-surface": "#33302b",
        "surface-bright": "#fff8f1",
        "brown-900": "#1A110A",
        "outline": "#83746b",
        "surface-container-highest": "#e8e1da",
        "on-secondary": "#ffffff",
        "cream-500": "#FFB733",
        "cream-100": "#fff3d0",
        "brown-700": "#5D4037",
        "on-tertiary-fixed": "#251a00",
        "on-secondary-container": "#7a4150",
        "accent-gold": "#d4af37",
        "accent-terracotta": "#c06c4d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "1rem",
        "component-gap": "1.5rem",
        "section-gap": "5rem",
        gutter: "1.5rem",
        "margin-desktop": "64px",
        unit: "4px",
      },
      fontFamily: {
        "display-xl": ["Playfair Display", "serif"],
        "display-xl-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-xl": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-xl": ["84px", { lineHeight: "90px", letterSpacing: "-0.04em", fontWeight: "900" }],
        "display-xl-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "900" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;