import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#6f4627",
        "on-primary": "#ffffff",
        "primary-container": "#8b5e3c",
        "on-primary-container": "#ffe3d1",
        secondary: "#884d5c",
        "on-secondary": "#ffffff",
        "secondary-container": "#feb2c3",
        "on-secondary-container": "#7a4150",
        tertiary: "#654c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#836300",
        "on-tertiary-container": "#ffe5ae",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fff8f1",
        "on-background": "#1e1b17",
        surface: "#fff8f1",
        "on-surface": "#1e1b17",
        "surface-variant": "#e8e1da",
        "on-surface-variant": "#51443c",
        outline: "#83746b",
        "outline-variant": "#d5c3b8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9f3eb",
        "surface-container": "#f4ede5",
        "surface-container-high": "#eee7df",
        "surface-container-highest": "#e8e1da",
        "surface-dim": "#dfd9d1",
        "surface-bright": "#fff8f1",
        "inverse-surface": "#33302b",
        "inverse-on-surface": "#f7f0e8",
        "inverse-primary": "#f4bb92",
        "surface-tint": "#805533",
        "primary-fixed": "#ffdcc5",
        "primary-fixed-dim": "#f4bb92",
        "on-primary-fixed": "#301400",
        "on-primary-fixed-variant": "#653d1e",
        "secondary-fixed": "#ffd9e0",
        "secondary-fixed-dim": "#feb2c3",
        "on-secondary-fixed": "#370b1a",
        "on-secondary-fixed-variant": "#6c3644",
        "tertiary-fixed": "#ffdf98",
        "tertiary-fixed-dim": "#f6bf1a",
        "on-tertiary-fixed": "#251a00",
        "on-tertiary-fixed-variant": "#5a4300",
        "gold-500": "#ffc726",
        "cream-500": "#ffb733",
        "terracotta-500": "#d4421e",
        "pastel-pink-500": "#ff406c",
        "brown-900": "#1a110a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg": ["Playfair Display", "serif"],
        "headline-xl": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;